### PR TITLE
Fix #17: compilation issues with gulp-sass + gulp-autoprefixer

### LINKED ISSUE #17: Compilation issues with gulp-sass + gulp-autoprefixer
Documenting a few issues I had while integrating in a Gulp build process.
# Issue 1

File: `src/select-css.css`
Line: 43

``` scss
@supports ( -webkit-appearance: none ) or ( appearance: none )
    /* Firefox <= 34 has a false positive on @supports( -moz-appearance: none )
     * @supports ( mask-type: alpha ) is Firefox 35+
     */
    or ( ( -moz-appearance: none ) and ( mask-type: alpha ) ) {
    ...
```

gulp-sass returns an error because the `@supports` statement is broken over two lines:

```
Error: Invalid CSS after "...earance: none )": expected "{", was "/* Firefox <= 34 ha"
        on line 56 of assets/scss/component/_custom-select.scss
>> @supports ( -webkit-appearance: none )
   --------------------------------------^
```
## Solution

Move the `@supports` statement to a single line like:

``` scss
/* Firefox <= 34 has a false positive on @supports( -moz-appearance: none )
 * @supports ( mask-type: alpha ) is Firefox 35+
 */
@supports ( -webkit-appearance: none ) or ( appearance: none ) or ( ( -moz-appearance: none ) and ( mask-type: alpha ) ) {
```
## Pull Request?

Not sure if @filamentgroup will take a PR for this. It's a little less clear what the comment applies to, but build tools are used by a fair number of developers. I think it's worth changing since it won't parse when imported as-is via gulp-sass (node-sass).
# FYI for Autoprefixer

The `@supports` statement will be removed from the compiled CSS if the default Autoprefixer config is used. Set `supports: false` your the Gulp task's config like:

```
.pipe(autoprefixer({
    browsers: ['last 2 versions', 'safari 6', 'ie >= 9', 'opera 12.1', 'ios 6', 'android 4'],
    cascade: false,
    supports: false
}))
```

Reference: https://github.com/postcss/autoprefixer#options

Make sure other `@supports` usages in your CSS supply their own prefixes with that config.

### PR DESCRIPTION
**Pull request by brendanfalkowski**
gulp-sass (node-sass) can’t compile with the multi-line @supports rule.

Moving the comment above `@supports` and making the rule a single line allows node-sass to compile it properly.

### CODE REVIEW

**Comment by brendanfalkowski** [comment]
Reference: #17

**Comment by brendanfalkowski** [comment]
Any change at getting this PR merged?

The @supports rule having new lines is breaking Sass compiler. Moving the comments above and keeping @supports on a single line fixes it.

**Comment by mrtobo** [comment]
This was failing for me when important via SASS. Thanks for doing this!

**Comment by ahmadalfy** [comment]
I don't know honestly why a simple PR like that isn't accepted instantly.

**Comment by antonsamper** [comment]
hi @zachleat, can you have a look at this PR. The manual workaround is a bit painful at the moment when using gulp-sass. thanks

**Comment by feitla** [comment]
+1. Would like to use this, but can't due to incompatibility with `gulp-sass`

**Comment by JDutil** [comment]
I was having compilation errors when upgrading to Webpack v2, and this resolved them. Would be Awesome to merge for a new package version. Thanks @brendanfalkowski

**Comment by jonscottclark** [comment]
Please @zachleat .. you're our only hope! Upgrading stuff that depended on `node-sass` due to Node 8.x.x introduced this issue in our build.

**Comment by JDutil** [comment]
If the maintainers of this library are unwilling to accept the patch I'd recommend we begin a new community repository. I don't mean to be disrespectful in anyway, but it would appear that they no longer have time to maintain this repository anymore. We should consider a way for more people to have commit access, so that there is not a bottleneck like this for compatibility moving forward, when there is clearly a need for the community to evolve that the maintainer doesn't share.

**Comment by zachleat** [comment]
Hmm, not sure how this one slipped under my radar. Need to reconfigure my email filters, maybe.

Regardless, merged—thank you!!

**Comment by jonscottclark** [comment]
Thank YOU @zachleat !

**Comment by JDutil** [comment]
Awesome thank you @zachleat 🎉

**Comment by zachleat** [comment]
This is now available on the 1.0.5 and 2.0.0 releases! Thanks everyone!

**Comment by zachleat** [comment]
Doing my best not to let this happen again but absolutely feel free to hit me up on Twitter if y’all see something lapse like this.

**Comment by brendanfalkowski** [comment]
@zachleat — Nice, I thought this PR was consigned to the abyss. Glad to see it merged!

**Pull request merged**
